export * from './bang.init'
export * from './bonus.init'
export * from './bullet.init'
export * from './coordinates.init'
export * from './game-object.init'
export * from './game.init'
export * from './player.init'
export * from './tank.init'
