export * from './bang.instance'
export * from './bonus.instance'
export * from './bullet.instance'
export * from './coordinates.instance'
export * from './game-object.instance'
export * from './game.instance'
export * from './player.instance'
export * from './tank.instance'
